export const modules={
 overview:{title:'经营工作台',subtitle:'订单、库存与资金实时汇总',icon:'DataAnalysis'},
 products:{title:'商品与库存',subtitle:'维护商品价格、箱规与商城独立库存',path:'products',columns:[['name','商品名称'],['spec','规格'],['retail','零售价','money'],['cloud_price','云代理价','money'],['center_price','中心价','money'],['owner_price','总代价','money'],['available','可售'],['locked','锁定'],['defective','残次'],['in_transit','采购在途'],['status','状态']]},
 orders:{title:'订单与履约',subtitle:'按商城查询真实订单及不可回溯的交易快照',path:'orders',columns:[['id','订单编号'],['order_type','订单类型'],['buyer_id','客户'],['total','实付款','money'],['refunded','已退款','money'],['merchant_no','收款商户'],['status','状态'],['created_at','创建时间']]},
 refunds:{title:'售后工作台',subtitle:'审批、退货验收与退款冲正分别留痕',path:'resources/refunds',columns:[['id','售后编号'],['order_id','原订单'],['refund_type','售后类型'],['qty','申请数量'],['refund_display','退款金额 / 积分 / 换货价值'],['reason','申请原因'],['status','状态']]},
 finance:{title:'资金与结算',subtitle:'审核通过不等于渠道到账，每笔资金可追溯',tabs:[['提现审核','resources/withdrawals'],['收益结算','resources/earnings'],['资金账本','resources/ledger'],['积分账户','resources/points'],['积分批次','resources/pointBatches'],['积分流水','resources/pointLedger'],['转赠双边记录','resources/pointTransfers'],['积分冻结复核','resources/pointRiskCases'],['渠道回执','resources/channelEvents'],['账单批次','resources/reconciliationBatches'],['对账明细','resources/reconciliationLines'],['调整复核','resources/reconciliationAdjustments']],columns:[['id','编号'],['member_id','账户'],['amount','金额','money'],['fee','手续费','money'],['net','到账金额','money'],['channel','渠道'],['status','状态'],['reason','说明']]},
 agents:{title:'代理与客户',subtitle:'云代理、分货中心、总代理与客户归属独立记录',tabs:[['代理名册','resources/agents'],['客户归属','resources/customers']],columns:[['id','代理编号'],['member_id','会员编号'],['rank_no','职级'],['parent_id','直接上级'],['shop_id','所属商城'],['status','状态']]},
 applications:{title:'业务申请审核',subtitle:'身份、结算账户和关系变更均经审核后生效',tabs:[['代理申请','documents/agent_application'],['联动关系审核','documents/link_relation'],['商城申请','documents/shop_application'],['商城交接','documents/shop_transfer'],['关系迁移','documents/migration'],['团队开店迁移','documents/team_migration'],['晋升申请','documents/promotion'],['降级审核','documents/downgrade'],['跨店采购','documents/cross_purchase'],['结算账户','documents/settlement_account'],['客服留言','documents/support'],['商品评价','documents/review'],['商品追评','documents/review_append'],['库存盘点','documents/stocktake']],columns:[['id','申请编号'],['member_id','申请人'],['status','审核状态'],['review_note','审核意见'],['created_at','提交时间']]},
 settings:{title:'营销与配置',subtitle:'配置按商城隔离，价格与分红使用版本快照',tabs:[['商城岗位','resources/staff'],['分红版本','rules'],['优惠券','documents/coupon'],['店铺装修','documents/decoration'],['页面配置','documents/page_schema'],['退货地址','documents/return_address'],['商品分类','documents/category'],['运费模板','documents/freight'],['价格促销','documents/promotion_rule'],['组合套餐','documents/bundle'],['邀请活动','documents/invitation_campaign'],['拼团配置','documents/group_campaign'],['拼团记录','resources/groups'],['拼团退款任务','resources/groupRefunds'],['积分规则','documents/points_rule'],['积分风控','documents/points_risk'],['考核指标','documents/assessment_rule'],['降级方案','documents/downgrade_rule'],['考核周期记录','resources/assessmentPeriods'],['联动2加1','documents/link_campaign'],['联动参与人','resources/linkParticipants'],['联动订单奖励','resources/linkRewards'],['消息模板','documents/notification_template'],['系统参数','documents/system_parameter'],['跨店规则','documents/cross_shop_policy']],columns:[['id','配置编号'],['cloud_bps','云代理（基点）'],['center_bps','中心（基点）'],['owner_bps','总代（基点）'],['effective_at','生效时间'],['created_by','操作人']]},
 audit:{title:'操作与账务审计',subtitle:'保留原始单据和变更记录，不覆盖历史账务',tabs:[['备份任务','backups'],['操作审计','resources/audit'],['库存流水','resources/inventory'],['账务流水','resources/ledger']],columns:[['id','编号'],['actor_id','操作人'],['action','操作'],['reference_id','关联单据'],['created_at','发生时间']]}
}
export const labels={RELEASED:'已解除冻结',RETAINED:'继续冻结',AGENT:'营销代理',BOSS:'营销老板',ARCHIVED:'历史版本',LINK_DIRECT:'联动直推订单奖',LINK_ORDER:'联动本人订单奖',LINK_PEER:'联动第二层平级奖',LINK_COST:'商城联动奖励支出',REFUND_LINK_DIRECT:'联动直推奖冲正',REFUND_LINK_ORDER:'联动订单奖冲正',REFUND_LINK_PEER:'联动平级奖冲正',REFUND_LINK_COST:'联动支出冲正',MANUAL:'人工导入',QUEUED:'等待处理',MATCHED:'账单一致',AMOUNT_MISMATCH:'金额差异',STATUS_MISMATCH:'回执待核验',REFERENCE_MISMATCH:'渠道流水不符',MERCHANT_MISMATCH:'商户号不符',OUT_OF_SCOPE:'商城归属不符',UNKNOWN_BUSINESS:'未找到业务单',RESOLVED:'调整已入账',RECON_ADJUST:'对账调整',PAYMENT:'支付',REFUND:'退款',REVIEW_REQUIRED:'生效条件变化待复核',RUNNING:'运行中',NONE:'尚无备份',APPLIED:'已生效',SCHEDULED:'已审核待生效',EXCHANGE_SHIPPED:'换货已发出',CLOSED:'已关闭',INACTIVE:'已下架',FROZEN:'已冻结',ACTIVE:'正常',PENDING:'待审核',UNPAID:'待付款',PAID:'已支付',SHIPPED:'已发货',COMPLETED:'已完成',CANCELLED:'已取消',REFUNDED:'已退款',APPROVED:'审核通过',REJECTED:'已驳回',WAIT_RETURN:'待退货验收',SUCCESS:'处理成功',FAILED:'处理失败',AVAILABLE:'可用',ONBOARDING:'进件中',MERGED:'已合并',MIGRATED:'已迁出',SUPPLEMENT:'待补充',WAIT_EXCHANGE:'待换货发出',DEALER_RETAIL:'经销商零售',DIRECT_RETAIL:'直营零售',AGENT_PURCHASE:'代理采购',WHOLESALE:'批发补货',DIRECT_SHIP:'整箱直发',POINTS:'积分兑换',REFUND_ONLY:'仅退款',RETURN:'退货退款',PARTIAL:'部分退款',EXCHANGE:'换货',BANK:'银行卡',WECHAT:'微信零钱',BALANCE:'系统余额',FORMING:'待成团',FORMED:'已成团',GROUP_FAILED:'拼团失败自动退款',RETRY:'等待重试',SUBMITTED:'已提交渠道',PROCESSING:'处理中',RETAIL:'零售毛利',LEVEL:'级差收益',PEER:'同级分红',INVITE_REWARD:'邀请订单奖励',INVITE_COST:'商城邀请奖励支出',PROMOTION_COST:'商城优惠承担',PEER_COST:'商城分红支出'}
Object.assign(labels, {
  RECEIPT: '订单收款', PAYOUT: '提现打款',
  REFUND_LEVEL: '级差收益冲正', REFUND_PEER: '同级分红冲正',
  REFUND_PEER_COST: '商城分红支出冲正', REFUND_RETAIL: '零售毛利冲正',
  REFUND_PROMOTION_COST: '商城优惠承担冲正',
  REFUND_INVITE_REWARD: '邀请订单奖励冲正', REFUND_INVITE_COST: '商城邀请奖励支出冲正'
})
export const settingFields={
 shop_transfer:[['operation','TRANSFER转让 / MERGE同拥有者合并 / CLOSE停业'],['newOwnerAgentId','新拥有者代理编号（转让必填）','number'],['targetShopId','目标商城编号（合并必填）','number'],['effectiveAt','生效时间（留空立即）','datetime'],['reason','交接原因及处置说明','textarea']],
 downgrade_rule:[['name','方案名称'],['enabled','启用季度/年度保级考核','switch'],['rank','适用职级（2中心 / 3总代）','number'],['periodKind','周期（QUARTER / YEAR）'],['periodMonths','周期月数（季度3 / 年度12）','number'],['firstPeriodStart','首次完整周期开始（YYYY-MM-DD）'],['failurePeriods','连续不达标周期数','number'],['salesThreshold','销售门槛（分）','number'],['directCount','下级人数门槛','number'],['repeatRate','复购率门槛（%）','number'],['operator','AND / OR / WEIGHTED'],['salesEnabled','销售指标','switch'],['peopleEnabled','人数指标','switch'],['repeatEnabled','复购指标','switch'],['salesWeight','销售权重（%）','number'],['peopleWeight','人数权重（%）','number'],['repeatWeight','复购权重（%）','number'],['scoreThreshold','权重达标分数','number'],['teamDepth','团队深度','number'],['includeSelf','包含本人销售','switch']],
 group_campaign:[['name','活动名称'],['enabled','启用拼团','switch'],['skuId','活动SKU'],['price','包邮团价（分，不叠券与积分）','number'],['size','成团人数（2至20）','number'],['hours','成团时限（小时）','number'],['startsAt','开始时间','datetime'],['expiresAt','结束时间','datetime']],
 return_address:[['name','退货收件人'],['phone','联系电话'],['address','详细退货地址','textarea']],
 cross_shop_policy:[['mode','模式：RETURN_HOME 返回原店；ALLOW_RETAIL 允许普通购买']],
 coupon:[['name','券名称'],['type','类型：FULL_REDUCTION / DISCOUNT / PRODUCT / NEWCOMER / TARGETED'],['rateBps','折扣基点（9折=9000）','number'],['skuIds','适用SKU（逗号分隔，空为全部）'],['memberIds','指定会员ID（逗号分隔）'],['threshold','门槛（分）','number'],['discount','优惠（分）','number'],['quantity','发放数量','number'],['expiresAt','到期时间','datetime']],
 decoration:[['name','商城名称'],['brandName','品牌名称'],['badge','直营标识'],['slogan','品牌标语'],['announcement','商城公告','textarea'],['customerPhone','客服电话'],['searchPlaceholder','搜索框占位文案'],['dealerSearchPlaceholder','经销商搜索框占位文案'],['asset','装修图片 FILE 编号（可用于轮播 image）','upload'],['assets','全局图片资源 JSON（资源名: FILE 编号或 URL）','json'],['banners','首页轮播配置 JSON（image/title/subtitle/buttonText/target/sort/enabled）','json'],['categories','首页分类配置 JSON（name/icon/target/sort/enabled）','json'],['homeProducts','首页推荐商品 SKU JSON 数组','json']],
 page_schema:[['screens','页面配置 JSON（键为 M01~G64，内容为现有 blocks/layout/nav/footer）','json'],['catalog','页面目录 JSON 数组（id/title/board）','json']],
 category:[['items','分类名称JSON数组（按显示顺序）','json']],
 freight:[['name','模板名称'],['billing','计费：FLAT固定 / COUNT按件 / WEIGHT重量'],['firstUnits','首件单位（重量填克）','number'],['stepUnits','续件单位（重量填克）','number'],['freightCents','首件运费（分）','number'],['extraFee','续件运费（分）','number'],['freeThreshold','包邮门槛（分）','number'],['remoteRegions','偏远省市（逗号分隔）'],['remoteFee','偏远附加费（分）','number']],
 promotion_rule:[['name','活动名称'],['priority','计算优先级（小数先）','number'],['exclusiveGroup','互斥组名称'],['stackPromotions','允许后续价格活动叠加','switch'],['tiers','阶梯JSON：threshold为分，rateBps为折扣','json'],['type','类型：FULL_REDUCTION / FULL_DISCOUNT / LIMITED / FLASH / MEMBER / TIER'],['rateBps','折扣基点（9折=9000）','number'],['skuIds','适用SKU（逗号分隔）'],['quantity','活动限量（0不限）','number'],['perMember','每人限量（0不限）','number'],['stackPoints','允许积分','switch'],['threshold','门槛（分）','number'],['discount','优惠（分）','number'],['startsAt','开始时间','datetime'],['expiresAt','截止时间','datetime'],['stackCoupon','允许叠加券','switch']],
 bundle:[['name','活动名称'],['type','类型：BUNDLE套餐 / ADDON加价购 / GIFT满赠 / EXCHANGE换购'],['items','商品JSON：[{"skuId":"cup","qty":1}]','json'],['qualifierSkuIds','门槛商品编号（逗号分隔，空为全部）'],['price','每套价格（分，赠品为0）','number'],['threshold','换购/满赠门槛（分）','number'],['quantity','活动总套数（0不限）','number'],['perMember','每人套数（0不限）','number'],['startsAt','开始时间','datetime'],['expiresAt','结束时间','datetime'],['priority','优先级','number'],['exclusiveGroup','互斥组'],['stackCoupon','叠加优惠券','switch'],['stackPoints','允许积分','switch'],['stackPromotions','叠加后续活动','switch']],
 invitation_campaign:[['name','活动名称'],['enabled','启用活动','switch'],['firstOrderReward','首单奖励最高（分）','number'],['thirdOrderReward','三单奖励最高（分）','number'],['rewardCap','每位邀请人累计发放上限（分）','number'],['minOrderAmount','有效商品实付门槛（分）','number'],['skuIds','有效SKU（逗号分隔，空为全部）'],['startsAt','开始时间','datetime'],['expiresAt','截止时间（完成订单为准）','datetime']],
 points_rule:[['name','规则名称'],['pointsPerYuan','抵扣1元所需积分','number'],['reviewPoints','评价奖励','number'],['purchaseRate','每元赠送积分','number'],['checkinPoints','签到积分','number'],['expiryDays','有效天数','number'],['deductionPercent','最大抵扣比例','number']],
 points_risk:[['singleLimit','单笔积分上限','number'],['dailyLimit','每日上限','number'],['monthlyLimit','每月上限','number'],['frequencyEnabled','启用转赠频率限制','switch'],['dailyCount','每日最多次数','number'],['windowSeconds','短时窗口（秒）','number'],['windowCount','短时最多次数','number'],['autoFreeze','频率异常自动冻结','switch']],
 assessment_rule:[['name','方案名称'],['salesThreshold','销售额门槛（分）','number'],['directCount','有效下级人数','number'],['repeatRate','复购率阈值','number'],['periodMonths','周期（月）','number'],['operator','指标关系（AND / OR / WEIGHTED）'],['periodKind','周期：ROLLING / MONTH / QUARTER / YEAR / CUSTOM'],['startDate','自定义开始日期（YYYY-MM-DD）'],['endDate','自定义结束日期（不含当天）'],['teamDepth','团队统计深度','number'],['includeSelf','包含本人销售','switch'],['teamCount','统计全团队人数','switch'],['salesEnabled','启用销售额','switch'],['peopleEnabled','启用人数指标','switch'],['repeatEnabled','启用复购率','switch'],['salesWeight','销售额权重（%）','number'],['peopleWeight','人数权重（%）','number'],['repeatWeight','复购权重（%）','number'],['scoreThreshold','加权达标分数','number'],['repeatMinOrders','复购订单门槛','number'],['repeatMinAmount','有效复购订单金额门槛（分）','number']],
 link_campaign:[['name','活动名称'],['enabled','启用活动','switch'],['directCount','有效新直推人数（必须为2）','number'],['minOrderAmount','有效商品订单门槛（分）','number'],['skuIds','参与SKU（逗号分隔）'],['rewardCap','个人累计奖励上限（分，退款不重置）','number'],['maxRewardPerOrder','单笔总奖励上限（含原三级收益，分）','number'],['totalRewardBps','总奖励占有效商品实付比例上限（10000=100%）','number'],['directReward','新代理首笔有效订单直推奖（固定分）','number'],['directBps','直推奖比例（基点，不能和固定金额同时填）','number'],['orderReward','本人有效订单奖（固定分）','number'],['orderBps','本人订单奖比例（基点）','number'],['peerReward','第二层同为营销老板的平级奖（固定分）','number'],['peerBps','平级奖比例（基点）','number'],['relationshipMode','KEEP_RELATION 保持 / EXIT_KEEP_TEAM 升移且带走团队 / EXIT_PASS_ONE 升移且留下1名'],['passedChild','留下的有效直推：EARLIEST最早 / LATEST最近'],['startsAt','开始时间','datetime'],['expiresAt','截止时间（完成订单为准）','datetime'],['confirmationFile','书面确认图片','upload'],['writtenConfirmed','已书面确认资格、关系和全部奖励条件','switch']],
 notification_template:[['name','模板名称'],['event','事件：ORDER_PAID / ORDER_SHIPPED / ORDER_COMPLETED / REFUND_UPDATED / WITHDRAW_UPDATED / INVENTORY_LOW / POINTS_UPDATED / AGENT_UPDATED / SYSTEM'],['title','消息标题（可空）'],['content','通知内容；支持 {{shop}}、{{reference}}、{{message}}','textarea']],
 system_parameter:[['name','参数名称'],['unpaidMinutes','支付有效期（分钟）','number'],['autoReceiveDays','自动收货（天）','number'],['afterSalesDays','售后期（天）','number'],['notifyPaid','支付站内通知','switch'],['notifyShipped','发货站内通知','switch'],['notifyRefund','售后站内通知','switch'],['notifyWithdrawal','提现站内通知','switch'],['notifyInventory','库存站内通知','switch']]
}
